title: Laura Torres
logo: "/images/1509D434-E549-4EFA-B072-21431F086918_1_201_a.jpeg?raw=true" 
description: > 
  <br>
 Graduate Student of Geographic and Enviromental System at the University of Maryland and Baltimore County (UMBC).
  <br>
  From Bogota-Colombia, where I got my Bachellor in Soclial Sciences at the La Gran Colombia University, also I have an Academic Specialization on Culture, Education and Politic from the Colombian National University.
  <br>
 Research interest migration flows, womens studies, education, community development and others. 
  <br><br>
  As Simon Rodriguez said, “I could be whatever I wanted, but I decide to build schools and teach”. 
  
  <br><br>
  <a href="https://www.linkedin.com/in/carolina-vargas-709902160?lipi=urn%3Ali%3Apage%3
  Ad_flagship3_profile_view_base_contact_details%3BWrQTF2BmRmydRILJVWVeuA%3D%3D">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

