title: Laura Torres
logo: "/images/1509D434-E549-4EFA-B072-21431F086918_1_201_a.jpeg?raw=true" 
description: > 
  <br>
  I am a current Graduate Student of Geographic and Enviromental System at the University of Maryland and Baltimore County (UMBC).<br>
  I am From Bogota-Colombia, where I got my Bachellor in Soclial Sciences at the La Gran Colombia University, also I have an Academic Specialization on Culture, Education and Politic from the Colombian National University.<br>
  I am on my second year of the Masters program, working on my research is based on themes as migration flows, womens studies, education, community development and others. <br><br>
  As Simon Rodriguez said, “I could be whatever I wanted, but I decide to build schools and teach”. <br>In light of this, my long-term goal is to be able to help and contribute in an active<br> 
  and constructive way to the development of the societal and academic systems in Latin 
  America, or perhaps aid the communication between Latin-American communities and other communities in the United States.<br><br>
  <a href="https://www.linkedin.com/in/carolina-vargas-709902160?lipi=urn%3Ali%3Apage%3
  Ad_flagship3_profile_view_base_contact_details%3BWrQTF2BmRmydRILJVWVeuA%3D%3D">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

